---
- name: "Ensure the python web app is deployed and configured with required resources."
  hosts: "db-dev"
  gather_facts: false
  become: true
  vars_prompt:
    - name: "mysql_root_user"
      prompt: "Enter the root user name for the MySQL instance"
    - name: "mysql_root_user_password"
      prompt: "Enter the root user password for the MySQL instance"
  roles:
    - { role: "python_web_app", db_root_user: "{{ mysql_root_user }}", db_root_user_password: "{{ mysql_root_user_password }}" }

