---
- name: "Ensure devops users are setup on all servers."
  hosts: "all"
  gather_facts: false
  become: true
  roles:
    - devops_users

- name: "Ensure dev & tester users are setup on jump servers."
  hosts: "pubjump pvtjump"
  gather_facts: false
  become: true
  roles:
    - dev_users
    - test_users

- name: "Ensure dev users are setup on dev environment servers."
  hosts: "dev"
  gather_facts: false
  become: true
  roles:
    - dev_users

- name: "Ensure tester users are setup on test environment servers."
  hosts: "test"
  gather_facts: false
  become: true
  roles:
    - test_users

