---
- name: "Ensure developer users are present."
  hosts: "dev"
  gather_facts: false
  become: true
  vars:
    developers:
      - { name: "rakesh", comment: "Rakesh Singh - Developer Team" }
      - { name: "anita", comment: "Anita Kumar - Developer Team"}
  tasks:
    - name: "Ensure dev group is present."
      group:
        name: "dev"
        state: "present"
    - name: "Ensure developer users are present."
      user:
        name: "{{ item.name }}"
        state: "present"
        create_home: "yes"
        home: "/home/{{ item.name }}"
        shell: "/bin/bash"
        comment: "{{ item.comment }}"
        groups: "dev"
        append: "yes"
      loop: "{{ developers }}"
    - name: "Ensure pub ssh key of dev users is copied to respective authorized_keys file on hosts."
      authorized_key:
        user: "{{ item.name }}"
        key: "{{ lookup('file', '../../pubans/files/user_pub_keys/developers/{{ item.name }}-key.pub') }}"
        state: "present"
      loop: "{{ developers }}"

