---
- name: "Ensure web server is configured."
  hosts: "web"
  gather_facts: false
  become: true
  tasks:
    - name: "Ensure required packages are installed."
      package:
        name:
          - "python3=3.10.4-0ubuntu2"
          - "python3-setuptools=59.6.0-1.2"
          - "python-dev-is-python3=3.9.2-2"
          - "build-essential=12.9ubuntu3"
          - "python3-pip=22.0.2+dfsg-1"
          - "python3-mysqldb=1.4.6-1build1"
        state: "present"

