---
- name: "Ensure web server is configured."
  hosts: "web"
  gather_facts: false
  become: true
  vars:
    proxy_server: "squid-proxy"
    proxy_port: "3128"
  tasks:
    - name: "Ensure required packages are installed."
      package:
        name:
          - "python3=3.10.4-0ubuntu2"
          - "python3-setuptools=59.6.0-1.2"
          - "python-dev-is-python3=3.9.2-2"
          - "build-essential=12.9ubuntu3"
          - "python3-pip=22.0.2+dfsg-1"
          - "python3-mysqldb=1.4.6-1build1"
          - "mysql-client=8.0.30-0ubuntu0.22.04.1"  # needed to connect to mysql db from app
        state: "present"
    - name: "Ensure python modules are installed using pip."
      pip:
        executable: "/usr/bin/pip3.10"
        name:
          - "flask==2.2.2"
          - "flask-mysql==1.5.2"
        extra_args: "--proxy=http://{{ proxy_server }}:{{ proxy_port }}"

