---
- name: "Ensure DB server is configured."
  hosts: "db"
  gather_facts: false
  become: true
  tasks:
    - name: "Ensure required packages are installed."
      package:
        name:
          - "mysql-server-8.0.26"   # MySQL server.
          - "mysql-8.0.26"          # MySQL client.
        state: "present"
    - name: "Ensure mysql server service is started and enabled."
      service:
        name: "mysqld.service"
        state: "started"
        enabled: "yes"

