---
# Playbook to enable password authentication on all servers.
- name: Ensure password authentication is enabled on all ubuntu hosts.
  hosts: ubuntu controller pubhosts
  gather_facts: false
  become: true
  tasks:
    - name: Ensure PasswordAuthentication is set to yes in /etc/ssh/sshd_config file.
      lineinfile:
        path: "/etc/ssh/sshd_config"
        regexp: "^PasswordAuthentication no"
        line: "PasswordAuthentication yes"
      notify:
        - "Restart SSH service"
  handlers:
    - name: "Restart SSH service"
      service:
        name: "ssh.service"
        state: "restarted"
- name: "Ensure password authentication is enabled in all redhat hosts."
  hosts: "redhat"
  gather_facts: false
  become: true
  tasks:
    - name: "Ensure 'Password Authentication no' is commented in /etc/ssh/sshd_config file."
      lineinfile:
        path: "/etc/ssh/sshd_config"
        regexp: "^PasswordAuthentication no"
        line: "#PasswordAuthentication no"
      notify:
        - "Restart SSH service"
    - name: "Ensure 'PasswordAuthentication yes' is uncommented in /etc/ssh/sshd_config file."
      lineinfile:
        path: "/etc/ssh/sshd_config"
        regexp: "^#PasswordAuthentication yes"
        line: "PasswordAuthentication yes"
      notify:
        - "Restart SSH service"
  handlers:
    - name: "Restart SSH service"
      service:
        name: "sshd.service"
        state: "restarted"


