---
- name: "Ensure squid package of version 5.2-1ubuntu4.2 is installed."
  ansible.builtin.apt:
    update_cache: "yes"
    name: "squid=5.2-1ubuntu4.2"
    state: "present"

- name: "Ensure squid config file is updated to allow all traffic."
  ansible.builtin.lineinfile:
    dest: "/etc/squid/squid.conf"
    regexp: "^http_access deny all"
    line: "http_access allow all"
  notify: "Restart SQUID service."

- name: "Ensure squid service is started and enabled to start at system startup."
  ansible.builtin.service:
    name: "squid.service"
    state: "started"
    enabled: "yes"

