---
- name: "Ensure git package is of latest version."
  ansible.builtin.package:
    name: "git"
    state: "latest"

- name: "Ensure .gitconfig file is templated for users."
  ansible.builtin.template:
    src: "gitconfig.j2"
    dest: "/home/{{ item.name }}/.gitconfig"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: "0644"
  loop: "{{ users }}"

