---
- name: "Ensure group & users for DevOps team members are created on all hosts."
  hosts: "all"
  gather_facts: false
  become: true
  tasks:
    - name: "Ensure devops group is present."
      group:
        name: "devops"
        state: "present"
    - name: "Ensure sudoers file for devops group is present."
      copy:
        content: "%devops ALL=(ALL) NOPASSWD:ALL\n"
        dest: "/etc/sudoers.d/devops_group"
        mode: "0440"
    - name: "Ensure devops team users are present and member of devops group."
      user:
        name: "{{ item.name }}"
        comment: "{{ item.comment }}"
        create_home: "yes"
        groups: "devops"
        append: "yes"
        home: "/home/{{ item.name }}"
        shell: "/bin/bash"
        state: "present"
      loop:
        - { name: "inderpal", comment: "Inderpal Singh - DevOps Team" }
        - { name: "omkar", comment: "Omkar Solaskar - DevOps Team" }
        - { name: "sarabjeet", comment: "Sarabjeet Singh - DevOps Team" }
    - name: "Ensure public ssh key for devops team users is copied to authorized_keys file."
      authorized_key:
        user: "{{ item.user }}" 
        key: "{{ lookup('file', '../files/user_pub_keys/devops/{{ item.user }}-key.pub') }}"
        state: "present"
      loop: 
        - { user: "inderpal" }
        - { user: "omkar" }
        - { user: "sarabjeet" }

- name: "Ensure .gitconfig file, git_repos dir & remote git repo are present on pubans host for all devops team members."
  hosts: "pubans"
  gather_facts: false
  become: true
  vars:
    devops_users:
      - "inderpal"
      - "omkar"
      - "sarabjeet"
  tasks:
    - name: "Copy gitconfig.j2 template file to .gitconfig file in each user's home dir."
      template:
        src: "../files/gitconfig.j2"
        dest: "/home/{{ item }}/.gitconfig"
        owner: "{{ item }}"
        group: "{{ item }}"
        mode: "0644"
      loop: "{{ devops_users }}"
    - name: "Create git_repos directory in home directory of each user."
      file:
        dest: "/home/{{ item }}/git_repos"
        state: "directory"
        owner: "{{ item }}"
        group: "{{ item }}"
        mode: "0775"
      loop: "{{ devops_users }}"
    - name: "Clone ansible-training-environments git repo to homedir/git_repos folder of each devops user."
      git:
        dest: "/home/{{ item }}/git_repos/ansible-training-environments"
        repo: "https://github.com/inderpal2406/ansible-training-environments.git"
      loop: "{{ devops_users }}"

